package llc.bokadev.kompass.core.util

import androidx.compose.runtime.Composable

data class AppStrings(
    val bottomHome: String,
    val bottomBrowse: String,
    val bottomActivities: String,
    val bottomEssentials: String,
    val chooseLanguage: String,
    val chooseLanguageSubtitle: String,
    val changeLanguage: String,
    val browseTitle: String,
    val browseSlug: String,
    val activitiesTitle: String,
    val activitiesSlug: String,
    val eventsTitle: String,
    val eventsSlug: String,
    val eventsSubtitle: String,
    val infoCenterTitle: String,
    val infoCenterSubtitle: String,
    val servicesTitle: String,
    val servicesSubtitle: String,
    val essentialsTitle: String,
    val essentialsSlug: String,
    val couldNotLoadCategories: String,
    val retry: String,
    val heroLocation: String,
    val heroTitle: String,
    val searchPlaceholder: String,
    val mustSee: String,
    val nearbyYou: String,
    val nearbyUnavailable: String,
    val nearbyEmpty: String,
    val upcomingEvents: String,
    val recentNews: String,
    val seeAll: String,
    val loadingKotor: String,
    val loadingLabel: String,
    val locationPromptTitle: String,
    val locationPromptBody: String,
    val continueLabel: String,
    val notNow: String,
    val activitiesIntro: String,
    val all: String,
    val noActivities: String,
    val noActivitiesForCategory: String,
    val premiumExtrasAvailable: String,
    val bestMorning: String,
    val bestAfternoon: String,
    val bestEvening: String,
    val anyTime: String,
    val noEventsForFilters: String,
    val noEventsYet: String,
    val myGuidesTitle: String,
    val myGuidesSlug: String,
    val unlockedAudioGuides: String,
    val noAudioGuidesTitle: String,
    val noAudioGuidesBody: String,
    val premiumActivities: String,
    val noPremiumActivitiesTitle: String,
    val noPremiumActivitiesBody: String,
    val itineraries: String,
    val customItineraries: String,
    val customItinerariesBody: String,
    val openPlaceholder: String,
    val openGuide: String,
    val viewActivity: String,
    val premiumTitle: String,
    val premiumSlug: String,
    val openAudioGuideNow: String,
    val premiumIntro: String,
    val unlocked: String,
    val processingCheckout: String,
    val unlockPricePrefix: String,
    val infoCenterSlug: String,
    val townNoticesSlug: String,
    val importantTownInformation: String,
    val affectedArea: String,
    val openSourceLink: String,
    val visitSource: String
)

private val stringsEn = AppStrings(
    bottomHome = "Home",
    bottomBrowse = "Browse",
    bottomActivities = "Activities",
    bottomEssentials = "Essentials",
    chooseLanguage = "Choose your language",
    chooseLanguageSubtitle = "Switch anytime while you explore.",
    changeLanguage = "Change language",
    browseTitle = "Browse",
    browseSlug = "What are you looking for",
    activitiesTitle = "Activities",
    activitiesSlug = "Go beyond the old town",
    eventsTitle = "Events",
    eventsSlug = "What’s on in Kotor",
    eventsSubtitle = "What is happening today, this week, and this month",
    infoCenterTitle = "Info Center",
    infoCenterSubtitle = "Town notices, disruptions, and practical updates",
    servicesTitle = "Services",
    servicesSubtitle = "Rent-a-car, boat rentals & more",
    essentialsTitle = "City Essentials",
    essentialsSlug = "Kotor",
    couldNotLoadCategories = "Could not load categories",
    retry = "Retry",
    heroLocation = "Kotor, Montenegro",
    heroTitle = "Experience the town",
    searchPlaceholder = "Search places, events…",
    mustSee = "Must See",
    nearbyYou = "Nearby You",
    nearbyUnavailable = "Location unavailable, showing closest curated spots around Old Town.",
    nearbyEmpty = "No nearby places available right now.",
    upcomingEvents = "Upcoming Events",
    recentNews = "Recent News",
    seeAll = "See all",
    loadingKotor = "Loading Kotor for you…",
    loadingLabel = "Loading",
    locationPromptTitle = "See what’s closest right now",
    locationPromptBody = "Allow location to show walkable places nearby and better local recommendations while you explore Kotor.",
    continueLabel = "Continue",
    notNow = "Not now",
    activitiesIntro = "Find hikes, UNESCO trails, medieval fortresses, village detours, and sunset ideas that move visitors outside the usual Kotor core.",
    all = "All",
    noActivities = "No activities available yet.",
    noActivitiesForCategory = "No activities match this category.",
    premiumExtrasAvailable = "Premium extras available",
    bestMorning = "Best in morning",
    bestAfternoon = "Best in afternoon",
    bestEvening = "Best in evening",
    anyTime = "Any time",
    noEventsForFilters = "No events match these filters",
    noEventsYet = "No events added yet",
    myGuidesTitle = "My Guides",
    myGuidesSlug = "Premium quick access",
    unlockedAudioGuides = "Unlocked audio guides",
    noAudioGuidesTitle = "No audio guides unlocked yet",
    noAudioGuidesBody = "Premium audio-ready activities will appear here for quick return.",
    premiumActivities = "Premium activities",
    noPremiumActivitiesTitle = "No premium activities available",
    noPremiumActivitiesBody = "Activities with deeper route context and guide access will appear here.",
    itineraries = "Itineraries",
    customItineraries = "Custom itineraries",
    customItinerariesBody = "Trip-building and structured route planning will live here once the itinerary flow is ready.",
    openPlaceholder = "Open placeholder",
    openGuide = "Open guide",
    viewActivity = "View activity",
    premiumTitle = "Premium",
    premiumSlug = "Unlock richer stories and planning",
    openAudioGuideNow = "OPEN AUDIO GUIDE NOW",
    premiumIntro = "Premium turns this into more than a free browse app. It unlocks guided storytelling and deeper trip planning designed for people who want more than the obvious Kotor route.",
    unlocked = "UNLOCKED",
    processingCheckout = "PROCESSING CHECKOUT...",
    unlockPricePrefix = "UNLOCK",
    infoCenterSlug = "Town notices and practical updates",
    townNoticesSlug = "Info Center",
    importantTownInformation = "Important town information",
    affectedArea = "Affected area",
    openSourceLink = "Open source link",
    visitSource = "Visit source"
)

private val stringsFr = stringsEn.copy(
    chooseLanguage = "Choisissez votre langue",
    chooseLanguageSubtitle = "Changez-la à tout moment pendant votre visite.",
    changeLanguage = "Changer de langue",
    browseTitle = "Explorer",
    browseSlug = "Que cherchez-vous",
    activitiesTitle = "Activités",
    activitiesSlug = "Allez au-delà de la vieille ville",
    eventsTitle = "Événements",
    eventsSlug = "Que se passe-t-il à Kotor",
    eventsSubtitle = "Ce qui se passe aujourd’hui, cette semaine et ce mois-ci",
    infoCenterTitle = "Centre d’infos",
    infoCenterSubtitle = "Avis municipaux, perturbations et mises à jour pratiques",
    servicesTitle = "Services",
    servicesSubtitle = "Location de voiture, bateaux et plus",
    essentialsTitle = "Essentiels de la ville",
    essentialsSlug = "Kotor",
    couldNotLoadCategories = "Impossible de charger les catégories",
    retry = "Réessayer",
    heroTitle = "Explorez\nla vieille ville",
    searchPlaceholder = "Rechercher lieux, événements…",
    nearbyYou = "Près de vous",
    nearbyUnavailable = "Localisation indisponible, nous montrons les lieux sélectionnés les plus proches de la vieille ville.",
    nearbyEmpty = "Aucun lieu à proximité pour le moment.",
    upcomingEvents = "Événements à venir",
    recentNews = "Actualités récentes",
    seeAll = "Voir tout",
    loadingKotor = "Chargement de Kotor…",
    loadingLabel = "Chargement",
    locationPromptTitle = "Voir ce qu’il y a près de vous",
    locationPromptBody = "Autorisez la localisation pour afficher les lieux accessibles à pied et de meilleures recommandations locales pendant votre découverte de Kotor.",
    continueLabel = "Continuer",
    notNow = "Plus tard",
    activitiesIntro = "Découvrez des randonnées, des sentiers UNESCO, des forteresses médiévales, des villages et des idées de coucher de soleil au-delà du cœur touristique habituel de Kotor.",
    all = "Tout",
    noActivities = "Aucune activité disponible pour le moment.",
    noActivitiesForCategory = "Aucune activité pour cette catégorie.",
    premiumExtrasAvailable = "Extras premium disponibles",
    bestMorning = "Idéal le matin",
    bestAfternoon = "Idéal l’après-midi",
    bestEvening = "Idéal le soir",
    anyTime = "À tout moment",
    noEventsForFilters = "Aucun événement ne correspond à ces filtres",
    noEventsYet = "Aucun événement ajouté pour le moment",
    myGuidesTitle = "Mes guides",
    myGuidesSlug = "Accès rapide premium",
    unlockedAudioGuides = "Guides audio débloqués",
    noAudioGuidesTitle = "Aucun guide audio débloqué",
    noAudioGuidesBody = "Les activités premium prêtes pour l’audio apparaîtront ici pour un accès rapide.",
    premiumActivities = "Activités premium",
    noPremiumActivitiesTitle = "Aucune activité premium disponible",
    noPremiumActivitiesBody = "Les activités avec plus de contexte et l’accès guide apparaîtront ici.",
    itineraries = "Itinéraires",
    customItineraries = "Itinéraires personnalisés",
    customItinerariesBody = "La création d’itinéraires et la planification structurée apparaîtront ici lorsque ce flux sera prêt.",
    openPlaceholder = "Ouvrir",
    openGuide = "Ouvrir le guide",
    viewActivity = "Voir l’activité",
    premiumTitle = "Premium",
    premiumSlug = "Débloquez plus d’histoires et de planification",
    openAudioGuideNow = "OUVRIR LE GUIDE AUDIO",
    premiumIntro = "Premium transforme l’app en bien plus qu’un simple outil de découverte. Il débloque un récit guidé et une planification plus riche pour ceux qui veulent plus que l’itinéraire évident de Kotor.",
    unlocked = "DÉBLOQUÉ",
    processingCheckout = "TRAITEMENT...",
    unlockPricePrefix = "DÉBLOQUER",
    infoCenterSlug = "Avis municipaux et mises à jour pratiques",
    importantTownInformation = "Informations importantes sur la ville",
    affectedArea = "Zone concernée",
    openSourceLink = "Ouvrir le lien source",
    visitSource = "Visiter la source"
)

private val stringsTr = stringsEn.copy(
    chooseLanguage = "Dilinizi seçin",
    chooseLanguageSubtitle = "Gezerken istediğiniz zaman değiştirebilirsiniz.",
    changeLanguage = "Dili değiştir",
    browseTitle = "Keşfet",
    browseSlug = "Ne arıyorsunuz",
    activitiesTitle = "Aktiviteler",
    activitiesSlug = "Eski şehrin ötesine geç",
    eventsTitle = "Etkinlikler",
    eventsSlug = "Kotor’da neler oluyor",
    eventsSubtitle = "Bugün, bu hafta ve bu ay neler oluyor",
    infoCenterTitle = "Bilgi Merkezi",
    infoCenterSubtitle = "Şehir duyuruları, aksaklıklar ve pratik güncellemeler",
    servicesTitle = "Hizmetler",
    servicesSubtitle = "Araç kiralama, tekne kiralama ve daha fazlası",
    essentialsTitle = "Şehir Temelleri",
    essentialsSlug = "Kotor",
    couldNotLoadCategories = "Kategoriler yüklenemedi",
    retry = "Tekrar dene",
    heroTitle = "Eski Şehri\nKeşfet",
    searchPlaceholder = "Mekân, etkinlik ara…",
    nearbyYou = "Yakınınızda",
    nearbyUnavailable = "Konum kullanılamıyor, Eski Şehir çevresindeki seçilmiş en yakın yerler gösteriliyor.",
    nearbyEmpty = "Şu anda yakınlarda yer yok.",
    upcomingEvents = "Yaklaşan Etkinlikler",
    recentNews = "Son Haberler",
    seeAll = "Tümünü gör",
    loadingKotor = "Kotor yükleniyor…",
    loadingLabel = "Yükleniyor",
    locationPromptTitle = "Yakınınızdakileri görün",
    locationPromptBody = "Kotor’u keşfederken yürünebilir yerleri ve daha iyi yerel önerileri göstermek için konuma izin verin.",
    continueLabel = "Devam et",
    notNow = "Şimdi değil",
    activitiesIntro = "Ziyaretçileri Kotor’un alışılmış merkezinin dışına taşıyan yürüyüşler, UNESCO rotaları, ortaçağ kaleleri, köy kaçamakları ve gün batımı fikirleri bulun.",
    all = "Tümü",
    noActivities = "Henüz aktivite yok.",
    noActivitiesForCategory = "Bu kategoriye uygun aktivite yok.",
    premiumExtrasAvailable = "Premium içerik mevcut",
    bestMorning = "Sabah en iyi",
    bestAfternoon = "Öğleden sonra en iyi",
    bestEvening = "Akşam en iyi",
    anyTime = "Her zaman",
    noEventsForFilters = "Bu filtrelere uygun etkinlik yok",
    noEventsYet = "Henüz etkinlik eklenmedi",
    myGuidesTitle = "Rehberlerim",
    myGuidesSlug = "Premium hızlı erişim",
    unlockedAudioGuides = "Kilidi açılmış sesli rehberler",
    noAudioGuidesTitle = "Henüz sesli rehber açılmadı",
    noAudioGuidesBody = "Premium sesli aktiviteler hızlı erişim için burada görünecek.",
    premiumActivities = "Premium aktiviteler",
    noPremiumActivitiesTitle = "Premium aktivite yok",
    noPremiumActivitiesBody = "Daha derin bağlam ve rehber erişimi olan aktiviteler burada görünecek.",
    itineraries = "Rotalar",
    customItineraries = "Özel rotalar",
    customItinerariesBody = "Gezi planlama ve yapılandırılmış rota akışı hazır olduğunda burada olacak.",
    openPlaceholder = "Aç",
    openGuide = "Rehberi aç",
    viewActivity = "Aktiviteyi görüntüle",
    premiumSlug = "Daha zengin hikâyeler ve planlama açın",
    openAudioGuideNow = "SESLİ REHBERİ AÇ",
    premiumIntro = "Premium, bunu sadece ücretsiz bir keşif uygulamasından fazlasına dönüştürür. Kotor’un en bilinen rotasından fazlasını isteyenler için rehberli anlatım ve daha derin gezi planlaması sunar.",
    unlocked = "AÇIK",
    processingCheckout = "ÖDEME İŞLENİYOR...",
    unlockPricePrefix = "AÇ",
    infoCenterSlug = "Şehir duyuruları ve pratik güncellemeler",
    importantTownInformation = "Önemli şehir bilgileri",
    affectedArea = "Etkilenen alan",
    openSourceLink = "Kaynak bağlantısını aç",
    visitSource = "Kaynağı ziyaret et"
)

private val stringsEs = stringsEn.copy(
    chooseLanguage = "Elige tu idioma",
    chooseLanguageSubtitle = "Puedes cambiarlo en cualquier momento mientras exploras.",
    changeLanguage = "Cambiar idioma",
    browseTitle = "Explorar",
    browseSlug = "Qué estás buscando",
    activitiesTitle = "Actividades",
    activitiesSlug = "Ve más allá del casco antiguo",
    eventsTitle = "Eventos",
    eventsSlug = "Qué pasa en Kotor",
    eventsSubtitle = "Qué está pasando hoy, esta semana y este mes",
    infoCenterTitle = "Centro de información",
    infoCenterSubtitle = "Avisos municipales, interrupciones y actualizaciones prácticas",
    servicesTitle = "Servicios",
    servicesSubtitle = "Alquiler de coches, barcos y más",
    essentialsTitle = "Esenciales de la ciudad",
    essentialsSlug = "Kotor",
    couldNotLoadCategories = "No se pudieron cargar las categorías",
    retry = "Reintentar",
    heroTitle = "Explora\nel casco antiguo",
    searchPlaceholder = "Buscar lugares, eventos…",
    nearbyYou = "Cerca de ti",
    nearbyUnavailable = "Ubicación no disponible; mostramos los lugares seleccionados más cercanos al casco antiguo.",
    nearbyEmpty = "No hay lugares cercanos ahora mismo.",
    upcomingEvents = "Próximos eventos",
    recentNews = "Noticias recientes",
    seeAll = "Ver todo",
    loadingKotor = "Cargando Kotor…",
    loadingLabel = "Cargando",
    locationPromptTitle = "Ver lo más cercano ahora",
    locationPromptBody = "Permite la ubicación para mostrar lugares a poca distancia y mejores recomendaciones locales mientras exploras Kotor.",
    continueLabel = "Continuar",
    notNow = "Ahora no",
    activitiesIntro = "Encuentra caminatas, rutas UNESCO, fortalezas medievales, desvíos a pueblos y planes para el atardecer fuera del núcleo habitual de Kotor.",
    all = "Todo",
    noActivities = "Aún no hay actividades disponibles.",
    noActivitiesForCategory = "No hay actividades para esta categoría.",
    premiumExtrasAvailable = "Extras premium disponibles",
    bestMorning = "Mejor por la mañana",
    bestAfternoon = "Mejor por la tarde",
    bestEvening = "Mejor por la noche",
    anyTime = "En cualquier momento",
    noEventsForFilters = "No hay eventos para estos filtros",
    noEventsYet = "Aún no se han añadido eventos",
    myGuidesTitle = "Mis guías",
    myGuidesSlug = "Acceso rápido premium",
    unlockedAudioGuides = "Guías de audio desbloqueadas",
    noAudioGuidesTitle = "Aún no hay guías de audio desbloqueadas",
    noAudioGuidesBody = "Las actividades premium con audio aparecerán aquí para volver rápidamente.",
    premiumActivities = "Actividades premium",
    noPremiumActivitiesTitle = "No hay actividades premium disponibles",
    noPremiumActivitiesBody = "Aquí aparecerán actividades con más contexto y acceso a guía.",
    itineraries = "Itinerarios",
    customItineraries = "Itinerarios personalizados",
    customItinerariesBody = "La planificación estructurada de rutas aparecerá aquí cuando esté lista.",
    openPlaceholder = "Abrir",
    openGuide = "Abrir guía",
    viewActivity = "Ver actividad",
    premiumSlug = "Desbloquea historias y planificación más profundas",
    openAudioGuideNow = "ABRIR GUÍA DE AUDIO",
    premiumIntro = "Premium convierte esto en mucho más que una app gratuita para explorar. Desbloquea narrativa guiada y una planificación más profunda para quienes quieren algo más que la ruta obvia de Kotor.",
    unlocked = "DESBLOQUEADO",
    processingCheckout = "PROCESANDO PAGO...",
    unlockPricePrefix = "DESBLOQUEAR",
    infoCenterSlug = "Avisos municipales y actualizaciones prácticas",
    importantTownInformation = "Información importante de la ciudad",
    affectedArea = "Zona afectada",
    openSourceLink = "Abrir enlace fuente",
    visitSource = "Visitar fuente"
)

private val stringsDe = stringsEn.copy(
    chooseLanguage = "Sprache wählen",
    chooseLanguageSubtitle = "Du kannst sie jederzeit während der Nutzung ändern.",
    changeLanguage = "Sprache ändern",
    browseTitle = "Entdecken",
    browseSlug = "Wonach suchst du",
    activitiesTitle = "Aktivitäten",
    activitiesSlug = "Mehr als nur die Altstadt",
    eventsTitle = "Veranstaltungen",
    eventsSlug = "Was in Kotor los ist",
    eventsSubtitle = "Was heute, diese Woche und diesen Monat passiert",
    infoCenterTitle = "Info-Center",
    infoCenterSubtitle = "Stadtmeldungen, Störungen und praktische Updates",
    servicesTitle = "Services",
    servicesSubtitle = "Mietwagen, Bootsverleih und mehr",
    essentialsTitle = "Stadt-Essentials",
    essentialsSlug = "Kotor",
    couldNotLoadCategories = "Kategorien konnten nicht geladen werden",
    retry = "Erneut versuchen",
    heroTitle = "Die Altstadt\nerkunden",
    searchPlaceholder = "Orte, Events suchen…",
    nearbyYou = "In deiner Nähe",
    nearbyUnavailable = "Standort nicht verfügbar, wir zeigen die nächstgelegenen kuratierten Orte rund um die Altstadt.",
    nearbyEmpty = "Derzeit keine Orte in der Nähe verfügbar.",
    upcomingEvents = "Bevorstehende Veranstaltungen",
    recentNews = "Aktuelle Meldungen",
    seeAll = "Alle ansehen",
    loadingKotor = "Kotor wird geladen…",
    loadingLabel = "Wird geladen",
    locationPromptTitle = "Sehen, was ganz in der Nähe ist",
    locationPromptBody = "Erlaube den Standortzugriff, um fußläufige Orte und bessere lokale Empfehlungen in Kotor anzuzeigen.",
    continueLabel = "Weiter",
    notNow = "Nicht jetzt",
    activitiesIntro = "Finde Wanderungen, UNESCO-Wege, mittelalterliche Festungen, Dörfer und Sonnenuntergangsideen jenseits des üblichen Kotor-Kerns.",
    all = "Alle",
    noActivities = "Noch keine Aktivitäten verfügbar.",
    noActivitiesForCategory = "Keine Aktivitäten für diese Kategorie.",
    premiumExtrasAvailable = "Premium-Extras verfügbar",
    bestMorning = "Am besten morgens",
    bestAfternoon = "Am besten nachmittags",
    bestEvening = "Am besten abends",
    anyTime = "Jederzeit",
    noEventsForFilters = "Keine Veranstaltungen für diese Filter",
    noEventsYet = "Noch keine Veranstaltungen vorhanden",
    myGuidesTitle = "Meine Guides",
    myGuidesSlug = "Premium-Schnellzugriff",
    unlockedAudioGuides = "Freigeschaltete Audioguides",
    noAudioGuidesTitle = "Noch keine Audioguides freigeschaltet",
    noAudioGuidesBody = "Premium-Aktivitäten mit Audio erscheinen hier für den schnellen Zugriff.",
    premiumActivities = "Premium-Aktivitäten",
    noPremiumActivitiesTitle = "Keine Premium-Aktivitäten verfügbar",
    noPremiumActivitiesBody = "Aktivitäten mit mehr Kontext und Guide-Zugang erscheinen hier.",
    itineraries = "Reisepläne",
    customItineraries = "Individuelle Reisepläne",
    customItinerariesBody = "Trip-Planung und strukturierte Routen erscheinen hier, sobald der Ablauf fertig ist.",
    openPlaceholder = "Öffnen",
    openGuide = "Guide öffnen",
    viewActivity = "Aktivität ansehen",
    premiumSlug = "Tiefere Geschichten und Planung freischalten",
    openAudioGuideNow = "AUDIOGUIDE ÖFFNEN",
    premiumIntro = "Premium macht daraus mehr als nur eine kostenlose Browse-App. Es schaltet geführtes Storytelling und tiefere Reiseplanung frei – für Menschen, die mehr wollen als die offensichtliche Kotor-Route.",
    unlocked = "FREIGESCHALTET",
    processingCheckout = "ZAHLUNG WIRD VERARBEITET...",
    unlockPricePrefix = "FREISCHALTEN",
    infoCenterSlug = "Stadtmeldungen und praktische Updates",
    importantTownInformation = "Wichtige Stadtinformationen",
    affectedArea = "Betroffener Bereich",
    openSourceLink = "Quelllink öffnen",
    visitSource = "Quelle besuchen"
)

fun appStringsFor(language: String): AppStrings = when (language) {
    "fr" -> stringsFr
    "tr" -> stringsTr
    "es" -> stringsEs
    "de" -> stringsDe
    else -> stringsEn
}

@Composable
fun rememberAppStrings(): AppStrings = appStringsFor(currentAppLanguage())
